#!/usr/bin/env node
/**
 * ---------------------------------------------------------------------------
 * VELLORA — media generator
 * ---------------------------------------------------------------------------
 * Vellora ships with its own art-directed plates so the template is complete
 * the moment you run `npm run dev`: no broken images, no third-party licences,
 * no API keys. Every plate is generated deterministically from its own key, so
 * regenerating produces byte-identical output.
 *
 *   npm run media
 *
 * Replacing them with photography does NOT require running this script — see
 * CUSTOMER_SETUP.md → "Change images".
 * ---------------------------------------------------------------------------
 */
import { mkdir, writeFile, readdir, rm } from "node:fs/promises";
import { existsSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { makeRng } from "./lib/rand.mjs";
import { plate } from "./lib/draw.mjs";
import { SCENES } from "./lib/scenes.mjs";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const outDir = join(root, "public", "media");

const LANDSCAPE = { w: 1800, h: 1200 };
const CINEMA = { w: 2400, h: 1600 };
const PORTRAIT = { w: 1200, h: 1500 };
const PORTRAIT_SCENE = { w: 1280, h: 1600 };
const PLAN = { w: 1600, h: 1200 };
const MAP = { w: 1600, h: 1000 };

/** Every plate the template ships with. Add rows here to extend the library. */
const GROUPS = [
  { prefix: "villa", scene: "villa", count: 10, size: LANDSCAPE },
  { prefix: "coastal", scene: "coastal", count: 8, size: LANDSCAPE },
  { prefix: "tower", scene: "tower", count: 8, size: LANDSCAPE },
  { prefix: "town", scene: "townhouse", count: 8, size: LANDSCAPE },
  { prefix: "estate", scene: "estate", count: 6, size: LANDSCAPE },
  { prefix: "land", scene: "land", count: 4, size: LANDSCAPE },
  { prefix: "aerial", scene: "aerial", count: 6, size: LANDSCAPE },
  { prefix: "detail", scene: "detail", count: 8, size: LANDSCAPE },
  { prefix: "interior", scene: "interior", count: 30, size: LANDSCAPE },
  { prefix: "portrait", scene: "portrait", count: 14, size: PORTRAIT },
  { prefix: "plan", scene: "plan", count: 12, size: PLAN },
  { prefix: "map", scene: "map", count: 8, size: MAP },
  { prefix: "editorial", scene: "editorial", count: 16, size: LANDSCAPE },
  // Wide cinematic plates for page heroes and full-bleed sections.
  { prefix: "cinema", scene: "cycle", count: 12, size: CINEMA },
  // Portrait plates, composed for 4:5 frames rather than cropped into them.
  { prefix: "room", scene: "interior", count: 12, size: PORTRAIT_SCENE },
  { prefix: "tall", scene: "tallcycle", count: 10, size: PORTRAIT_SCENE },
];

const CINEMA_CYCLE = ["coastal", "villa", "estate", "tower", "coastal", "villa"];
const TALL_CYCLE = ["townhouse", "detail", "villa", "tower", "coastal", "detail", "townhouse", "estate", "detail", "villa"];

function buildKeys() {
  const keys = [];
  for (const g of GROUPS) {
    for (let i = 1; i <= g.count; i++) {
      const id = String(i).padStart(2, "0");
      const scene =
        g.scene === "cycle"
          ? CINEMA_CYCLE[(i - 1) % CINEMA_CYCLE.length]
          : g.scene === "tallcycle"
            ? TALL_CYCLE[(i - 1) % TALL_CYCLE.length]
            : g.scene;
      keys.push({ key: `${g.prefix}-${id}`, scene, ...g.size });
    }
  }
  return keys;
}

async function main() {
  const keys = buildKeys();
  if (existsSync(outDir)) {
    for (const f of await readdir(outDir)) {
      if (f.endsWith(".svg")) await rm(join(outDir, f));
    }
  }
  await mkdir(outDir, { recursive: true });

  let bytes = 0;
  for (const item of keys) {
    const compose = SCENES[item.scene];
    if (!compose) throw new Error(`Unknown scene "${item.scene}" for ${item.key}`);
    const rng = makeRng(`vellora::${item.key}`);
    const scene = compose(rng, item.w, item.h);
    const svg = plate({
      w: item.w,
      h: item.h,
      defs: scene.defs,
      body: scene.body,
      grainOpacity: scene.grainOpacity ?? 0.15,
      vignette: scene.vignette ?? 0.48,
    });
    await writeFile(join(outDir, `${item.key}.svg`), svg, "utf8");
    bytes += Buffer.byteLength(svg);
  }

  // Emit a typed key union so a typo in /data becomes a compile error.
  const ts = `// AUTO-GENERATED by \`npm run media\` — do not edit by hand.
// Regenerate after adding plates in scripts/generate-media.mjs.

export const MEDIA_KEYS = [
${keys.map((k) => `  "${k.key}",`).join("\n")}
] as const;

export type MediaKey = (typeof MEDIA_KEYS)[number];

/** Intrinsic dimensions of each shipped plate, used for aspect-ratio hints. */
export const MEDIA_DIMENSIONS: Record<MediaKey, { width: number; height: number }> = {
${keys.map((k) => `  "${k.key}": { width: ${k.w}, height: ${k.h} },`).join("\n")}
};
`;
  await writeFile(join(root, "lib", "media-keys.ts"), ts, "utf8");

  console.log(
    `Generated ${keys.length} plates → public/media  (${(bytes / 1024).toFixed(0)} KB total, avg ${(bytes / keys.length / 1024).toFixed(1)} KB)`,
  );
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
